# Generated by Django 6.1.1 on 2026-09-23 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_cs",
                    models.CharField(max_length=150, verbose_name="Назва (CS)"),
                ),
                (
                    "description_cs",
                    models.TextField(blank=True, verbose_name="Опис (CS)"),
                ),
                (
                    "name_uk",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Назва (UK)"
                    ),
                ),
                (
                    "description_uk",
                    models.TextField(blank=True, verbose_name="Опис (UK)"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, max_digits=8, verbose_name="Ціна (Kč)"
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=45,
                        help_text="Скільки хвилин триває процедура (наприклад, 30, 45, 60)",
                        verbose_name="Тривалість (у хвилинах)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна послуга"),
                ),
            ],
            options={
                "verbose_name": "Послуга",
                "verbose_name_plural": "Послуги",
                "ordering": ["price"],
            },
        ),
        migrations.CreateModel(
            name="WorkingDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Дата")),
                ("start_time", models.TimeField(verbose_name="Початок роботи")),
                ("end_time", models.TimeField(verbose_name="Кінець роботи")),
                (
                    "is_day_off",
                    models.BooleanField(default=False, verbose_name="Вихідний день"),
                ),
            ],
            options={
                "verbose_name": "Робочий день",
                "verbose_name_plural": "Робочі дні",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_name",
                    models.CharField(max_length=100, verbose_name="Ім'я клієнта"),
                ),
                (
                    "client_phone",
                    models.CharField(max_length=20, verbose_name="Телефон клієнта"),
                ),
                ("date", models.DateField(verbose_name="Дата візиту")),
                ("start_time", models.TimeField(verbose_name="Час початку")),
                ("end_time", models.TimeField(verbose_name="Час закінчення")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Підтверджено"),
                            ("cancelled", "Скасовано"),
                        ],
                        default="confirmed",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата створення запису"
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="bookings.service",
                        verbose_name="Послуга",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запис",
                "verbose_name_plural": "Записи",
                "ordering": ["-date", "-start_time"],
            },
        ),
    ]
