# Generated by Django 6.1.1 on 2026-09-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_booking_cancel_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="buffer_minutes",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Час на дезінфекцію, прибирання та відпочинок",
                verbose_name="Технічна перерва після (хв)",
            ),
        ),
    ]
