# Generated by Django 6.1.1 on 2026-09-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_service_buffer_minutes"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "cancelled"), _negated=True),
                fields=("date", "start_time"),
                name="unique_active_booking_slot",
            ),
        ),
    ]
